### ISSUE TITLE
Non-Nullable Field Set NULL During Upsert, Causes Integrity Error

### ISSUE THREAD

**Issue by jjorissen52** [SectorLabs/django-postgres-extra#106]
When trying to use `bulk_upsert` to perform a bulk update, if a non-nullable field without a default (`non_nullable_title` below) is not part of the upsert dict, the upsert will fail. Zipped [sample project](https://github.com/SectorLabs/django-postgres-extra/files/4984075/cannot_upsert.zip).

### Model
```python
# simple_model.models
from django.db import models
from psqlextra.models import PostgresModel


class ModelWithNonNullable(PostgresModel):
    title = models.CharField(max_length=10, null=True)
    non_nullable_title = models.CharField(max_length=10, null=False)
```

### Test
```python
# simple_model.tests
import django
from django.test import TestCase

from simple_model.models import ModelWithNonNullable


class TestNonNullableModel(TestCase):

    def test_cannot_upsert(self):
        ModelWithNonNullable.objects.bulk_create([
            ModelWithNonNullable(
                title="mytitle",
                non_nullable_title="2ndtitle"
            ),
        ])
        _id = ModelWithNonNullable.objects.get(title='mytitle').id
        ModelWithNonNullable.objects.bulk_upsert(['id'], [{'id': _id, 'non_nullable_title': 'newtitle'}, ])

        assert ModelWithNonNullable.objects.count() == 1
        instance = ModelWithNonNullable.objects.first()
        assert instance.id == _id
        assert instance.title == "mytitle"

        # upsert works here as expected
        assert instance.non_nullable_title == "newtitle"

        with self.assertRaises(django.db.utils.IntegrityError):
            ModelWithNonNullable.objects.bulk_upsert(['id'], [{'id': _id, 'title': 'newtitle'}, ])
```

### Output
```bash
$ python manage.py test

Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.027s

OK
```

### Caught Exception
```
psycopg2.errors.NotNullViolation: null value in column "non_nullable_title" violates not-null constraint
DETAIL:  Failing row contains (1, newtitle, null).
```

### Reproduce
1. Download and inflate [zip](https://github.com/SectorLabs/django-postgres-extra/files/4984075/cannot_upsert.zip)
2. activate virtual environment
3. pip install -r requirements.txt
4. docker-compose up db
5. python manage.py migrate
6. python manage.py test

**Comment by rvinzent** [comment]
Is this package being maintained anymore? This is a huge issue

**Comment by Photonios** [comment]
I fail to see what the bug is here. You're trying to upsert a record that has a row in it that fails the constraints you set up.

```
ModelWithNonNullable.objects.bulk_upsert(['id'], [{'id': _id, 'title': 'newtitle'}, ])
```

Correctly raises `IntegrityError` as you _must_ specify `non_nullable_title`. Since it has no default, Postgres has no choice but to reject the record.

Your query set translates to:

```
INSERT INTO "simple_model_modelwithnonnullable" ("id", "title") VALUES (1, 'title') ON CONFLICT ("id") DO UPDATE SET "id" = EXCLUDED."id", "title" = EXCLUDED."title" RETURNING "id"
```

You can try this in Postgres and validate that it raises the same error.

**Comment by rvinzent** [comment]
@Photonios the feature / bug is that the existing value for `non_nullable_title` should be used, instead `null` is used in the statement. 

This is a partial update on the record. If `non_nullable_title` is not specified, then it should not be updated. `bulk_upsert` tries to update to `null`.

It should not attempt to update the field at all, like in the working example above
```python
 ModelWithNonNullable.objects.bulk_upsert(['id'], [{'id': _id, 'non_nullable_title': 'newtitle'}, ])
```
The `title` field is not updated, as expected.

Now when trying the same thing with the other field
```python
ModelWithNonNullable.objects.bulk_upsert(['id'], [{'id': _id, 'title': 'newtitle'}, ])
```

The expected behavior would be to update the `title` field to `"newtitle"`, and leave `non_nullable_title` as the existing value. Instead, the actual behavior is to try to update `non_nullable_title` to `NULL`, which is unintuitive based on the behavior of the working upsert.

Why is it trying to update the field to `NULL`? Just leave it alone, same thing that happens for the nullable field.

Please reconsider opening this ticket.
