### ISSUE TITLE
When an empty array is passed to bulk_insert it raises StopIteration

### ISSUE THREAD

**Issue by sazary** [SectorLabs/django-postgres-extra#132]
Hi  

If you pass an empty array to `bulk_insert` it raises an `StopIteration` exception. On contrast, the default `bulk_create` of django itself just returns an empty array.

This is the stack trace that occurs:

```
~/.virtualenvs/miare36/lib/python3.6/site-packages/psqlextra/query.py in bulk_insert(self, rows, return_model, using)
    151                 deduped_rows.append(row)
    152 
--> 153         compiler = self._build_insert_compiler(deduped_rows, using=using)
    154         objs = compiler.execute_sql(return_id=True)
    155         if return_model:

~/.virtualenvs/miare36/lib/python3.6/site-packages/psqlextra/query.py in _build_insert_compiler(self, rows, using)
    398         objs = []
    399         rows_iter = iter(rows)
--> 400         first_row = next(rows_iter)
    401         field_count = len(first_row)
    402         for index, row in enumerate(chain([first_row], rows_iter)):

StopIteration: 

```

I think it's better to be consistent with django's API.

Python version: 3.6.9
Django version: 2.2.6
django-postgres-extra version: 2.0.2

**Comment by Photonios** [comment]
This will work properly in v2.0.3.

**Comment by aehlke** [comment]
This was closed but I just ran into it with latest release

**Comment by franga2000** [comment]
I can confirm as well that this happens on `v2.0.6`.  It's extra bad when used in an async context (through `sync_to_async`), because an unhandled `StopIteration` causes it to hang the coroutine forever (through a [very obscure Python error](https://github.com/python/cpython/blob/fd38a2f0ec03b4eec5e3cfd41241d198b1ee555a/Lib/asyncio/futures.py#L275-L277)).

I've opened a PR: #196
