### ISSUE TITLE
make `python manage.py pgpartition` smarter

### ISSUE THREAD

**Issue by jhd4tmr** [SectorLabs/django-postgres-extra#185]
Currently, when adding new range partition will not acquire the old partition and automatically distribute the time evenly.
For example, if i add 10 partitions ahead with 3 months seperated, next time i have to check the start time using `PostgresTimePartitioningStrategy` or it will occur a `overlap partition` error. Because range 2022-6-1 to 2022-9-1 and range 2022-5-1 to 2022-8-1 are both accpetable for the 3 months range partition.

**Comment by vne** [comment]
@j4tmr Were you able to figure out how to fix this? I'm having a similar issue.

Here's my partitioning config:
`manager = PostgresPartitioningManager([
    PostgresPartitioningConfig(
        model=Model_A,
        strategy=PostgresCurrentTimePartitioningStrategy(
            size=PostgresTimePartitionSize(months=3),
            count=2,
        )
    ),    
    PostgresPartitioningConfig(
        model=Model_B,
        strategy=PostgresCurrentTimePartitioningStrategy(
            size=PostgresTimePartitionSize(months=3),
            count=2,
        )
    ),
    PostgresPartitioningConfig(
        model=Model_C,
        strategy=PostgresCurrentTimePartitioningStrategy(
            size=PostgresTimePartitionSize(months=3),
            count=6,
        )
    ),
])
`

If I add a new model D to this config and run the pgpartition command, I get `django.db.utils.ProgrammingError: partition "model_a_2025_jan" would overlap partition "model_a_2024_nov"` and the process stops. As a result, model B, model C and model D are never considered. If I comment model A from the config, other models are processed correctly. Note that if I run pgpartition every day, there is a moment each X months when overlap doesn't occur and new partitions are created. We are using this as a workaround. However, if model B needs to create a new partition, and model A crashes because of overlapping, it seems like model B will never be considered.

@Photonios I'm using the config from https://django-postgres-extra.readthedocs.io/en/master/table_partitioning.html#time-based-partitioning. Django 3.2, django-postgres-extra==2.0.8. I'll be most grateful if someone could help me figure out what am I missing.

If crashing in such cases is the expected behavior, I'd suggest at least to consider each partitioning config independently, so that crash in one doesn't affect others. I think I can work on a patch if you agree on the proposed approach.
