### ISSUE TITLE
Merge changes with `django`

### ISSUE THREAD

**Issue by baseplate-admin** [SectorLabs/django-postgres-extra#219]
Hi, Thanks for creating this awesome repository. 

But i have a question :
Is there any particular reason that this repository is being developed outside of `django` core?

Can you guys join and merge efforts?

Thanks :D

**Comment by Photonios** [comment]
It is developed outside Django core because we have different goals than the Django project. This project intends to make Postgres-specific feature usable with the Django ORM. Django's goal is to provide an all-round ORM that works well with a variety of databases.

Of course, some of the ideas from this project might find their way into Django core, but that isn't the primary goal.
