### ISSUE TITLE
bulk_insert return only one value on ConflictAction.NOTHING

### ISSUE THREAD

**Issue by Amoki** [SectorLabs/django-postgres-extra#63]
I'm using 1.21a12

My code:
```python
    classifications_payload = [
        {
            "project_id": project_id,
            "name": classification["name"],
        }
        for classification in classifications
    ]
    print(len(classifications_payload)) # --> 12

    classification_objects = Classification.objects.on_conflict(
        ["project_id", "name", "notation"], ConflictAction.NOTHING
    ).bulk_insert(classifications_payload, return_model=True)

    print(len(classification_objects)) # --> 1
```

Digging a little deeper, I can log : 
```python
# manager/manager.py
    def bulk_insert(self, rows, return_model=False):
        if self.conflict_target or self.conflict_action:
            compiler = self._build_insert_compiler(rows)
            objs = compiler.execute_sql(return_id=True)
            print(len(rows)) # --> 12
            print(len(objs)) # --> 1
            if return_model:
                a = [self.model(**dict(r, **k)) for r, k in zip(rows, objs)]
                print(len(a)) # --> 1
                return a
            else:
                return [dict(r, **k) for r, k in zip(rows, objs)]
```

Everything works fine if I use `ConflictAction.UPDATE`.
Is this a normal behavior ?

**Comment by Photonios** [comment]
This is actually trickier than it seems. PostgreSQL's `ON CONFLICT DO NOTHING` only returns rows that were created. Conflicting rows for which nothing happened are not returned at all.

The current implementation is a trick described in: https://stackoverflow.com/questions/40323799/return-rows-from-insert-with-on-conflict-without-needing-to-update

This trick works well when trying to insert a single row (with `NOTHING` as the conflict action). However, it does not work well when trying to insert multiple rows because there is no good way of determining which rows were affected. PostgreSQL by default only returns newly inserted rows and does no reporting on rows that were ignored (conflicted). 

The trick also has a major downside in the sense that it actually uses `ON CONFLICT DO UPDATE`, which does no update. It does however create a new tuple internally, this bloating the table a little bit. Usually this is not a problem, but it is not the most efficient way of doing it. When inserting a single row, this is not a big problem, however, with bulk upserts, it might be.

I have yet to find a good solution for this. I am currently thinking of removing the trick and only returning rows that were created (as PostgreSQL does automatically). This is the most efficient and if you need the full set of rows, you can query them separately.

My apologies for the late reply. As you can see, this is not a simple problem. I have tried to solve it multiple times. The available solutions are complicated, risky and will for sure cause backwards incompatibility and none of them are perfect.

**Comment by Photonios** [comment]
This is being addressed in v2.
